version: '2'
services:
  postgresql:
    image: postgres:10.4
    container_name: postgresql
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgresql: {}
