default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: territory-test-blog_development

test:
  <<: *default
  database: territory-test-blog_test

production:
  <<: *default
  database: territory-test-blog_production
  username: territory-test-blog
  password: <%= ENV['TERRITORY-TEST-BLOG_DATABASE_PASSWORD'] %>
